version: "3"
services:
  db:
    image: mysql:8.0
    container_name: mysql_database
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_TCP_PORT: ${MYSQL_PORT}
    ports:
      - ${MYSQL_PORT}:${MYSQL_PORT}

    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data: ~
